# Configurações do banco de dados
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eco_manager
    username: postgres
    password: admin594

  # Configurações adicionais do JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  # Configurações do servidor
  config:
    import: optional:file:.env[.properties]
  application:
    name: listaTarefaApplication
  profiles:
    active: test

  # Configurações de e-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAILSENDER_USERNAME}
    password: ${EMAILSENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

# Configurações de autenticação JWT
auth:
  jwt:
    token:
      secret: ${JWT_TOKEN_SECRET}
      expiration: 2
    refresh-token:
      expiration: 8

server:
  port: 8080